#!/bin/bash

find=$FIND
if [ -z "$find" ]; then
	find=find
fi;

directory=$1
if [ -z "$directory" ]
then
	directory=.
fi

echo directory is $directory

clean() {
	$find $directory -name $1 -exec rm {} \;
}

echo "du total:"
du -kc $directory | tail -1
echo "cleaning..."
clean '*.cobra.cs'
clean 'test-*.cs'
clean 'r'
clean 'r-*'
clean '*.exe'
clean '*.dll'
clean '*.pdb'
clean '*.mdb'
clean '*.tmp'
clean 'cobra-exc*.html'
svn up 720-libraries/400-other/Foo.iSeries.dll
echo "du total:"
du -kc $directory | tail -1
