#!/bin/bash

find=$FIND
if [ -z "$find" ]; then
	find=find
fi;

directory=$1
if [ -z "$directory" ]
then
	directory=.
fi

echo "clean: directory = $directory"

clean() {
	# to-do:
#	find_exclude_scc='-type d -name .svn -prune -o'
	find_exclude_scc=
	$find $directory -name "$1" $find_exclude_scc -exec rm {} \;
}

echo "du total:"
du -kc $directory | tail -1
echo "cleaning..."
clean '*.cobra.cs'
clean 'Native*.cs'
clean 'test-*.cs'
clean 'r'
clean 'r-*'
clean '*.exe'
clean '*.dll'
clean '*.pdb'
clean '*.mdb'
clean '*.tmp'
clean 'cobra-exc*.html'
svn up 720-libraries/400-other
echo "du total:"
du -kc $directory | tail -1

echo 'clean: done'

