#!/bin/bash

find=$FIND
if [ -z "$find" ]; then
	find=find
fi;

clean() {
	$find . -name $1 -exec rm {} \;
}

echo "du total:"
du -kc | tail -1
echo "cleaning..."
clean '*.cobra.cs'
clean 'test-*.cs'
clean 'r'
clean 'r-*'
clean '*.exe'
clean '*.dll'
clean '*.pdb'
clean '*.mdb'
clean '*.tmp'
clean 'cobra-exc*.html'
echo "du total:"
du -kc | tail -1
