#!/bin/bash
# Build script for java sources for cobra
# Compile java source classes for java cobra RTL
# copy them and std sig files to Source dir 

[ -d classes ] || mkdir classes
[ -d classes/cobra/lang ] && rm -rf classes/cobra/lang/*
EXCEPTIONS="AssertException.java InvariantException.java RequireException.java EnsureException.java NonNilCastException.java DynamicOperationException.java"
javac -d classes SourceSite.java CobraImp.java CobraCore.java Delegate.java ${EXCEPTIONS} CobraDirectString.java
[ $? == 0 ] || exit
jar cvf CobraLang.jar -C classes .
[ $? == 0 ] || exit
cp CobraLang.jar ../..

#echo 'pkgSig for CobraLang.jar'
java -cp '.;CobraLang.jar'  PkgSig -j CobraLang.jar > CobraLang.jar.sig
cp CobraLang.jar.sig  ../..


## assume rt.jar, java.util and java.lang sigfiles already exist and are static
#cp CobraLang.jar.sig rt.jar.sig java.util.sig java.lang.sig ../..
