#!/bin/bash
# Build script for java sources for cobra
# Compile java source classes for java cobra RTL
# copy them and std sig files to Source dir 

CORE_RTL='CobraCore.jar'

[ -d classes ] || mkdir classes
[ -d classes/cobra/lang ] && rm -rf classes/cobra/lang/*
EXCEPTIONS="AssertException.java InvariantException.java RequireException.java EnsureException.java NonNilCastException.java DynamicOperationException.java ExpectException.java CheckedExceptionWrapper.java"
javac -Xlint:unchecked -d classes SourceSite.java CobraImp.java CobraCore.java Delegate.java DelegateO.java Pair.java ${EXCEPTIONS} CobraDirectString.java
[ $? == 0 ] || exit
jar cvf ${CORE_RTL} -C classes .
[ $? == 0 ] || exit
cp ${CORE_RTL} ../..

#echo 'pkgSig for '${CORE_RTL}
#java -cp "PkgSig.jar;${CORE_RTL}"  PkgSig -j ${CORE_RTL} > ${CORE_RTL}.sig
#cp ${CORE_RTL}.sig  ../..


## assume rt.jar, java.util and java.lang sigfiles already exist and are static
#cp ${CORE_RTL}.sig rt.jar.sig java.util.sig java.lang.sig ../..
