#!/bin/bash
DIR=`dirname $0`
if [ ! -f "$DIR/CobraLang.cobra" ]; then
	REALPATH=`readlink $0`
	if [ -f $REALPATH ]; then
		DIR=`dirname $REALPATH`
	else
		echo "error: cannot find CobraLang.cobra"
		exit 1
	fi
fi
mono "$DIR/cobra.exe" $*
