#!/bin/bash
DIR=`dirname $0`
if [ ! -d "$DIR/Cobra.Core" ]; then
	REALPATH=`readlink $0`
	if [ -f $REALPATH ]; then
		DIR=`dirname $REALPATH`
	else
		echo "error: cannot find Cobra.Core"
		exit 1
	fi
fi
mono --debug "$DIR/cobra.exe" $*
