#!/bin/bash
DIR=`dirname $0`
if [ ! -d "$DIR/Cobra.Lang" ]; then
	REALPATH=`readlink $0`
	if [ -f $REALPATH ]; then
		DIR=`dirname $REALPATH`
	else
		echo "error: cannot find Cobra.Lang"
		exit 1
	fi
fi
mono "$DIR/cobra.exe" $*
