#!/bin/bash
DIR=`dirname $0`
if [ -f "$DIR/CobraLang.cobra" ]; then
	echo "" > /dev/null
else
	REALPATH=`readlink -f $0`
	if [ -f $REALPATH ]; then
		DIR=`dirname $REALPATH`
	else
		echo "error: cannot find CobraLang.cobra"
		exit 1
	fi
fi
mono "$DIR/cobra.exe" $*
