#!/bin/bash
target='Snapshot'
mkdir -p $target
cp cobra $target/
cp cobra.exe $target/
if [ -e cobra.pdb ]
	then
		cp cobra.pdb $target/
	else
		rm -f $target/cobra.pdb
fi
if [ -e cobra.mdb ]
	then
		cp cobra.mdb $target/
	else
		rm -f $target/cobra.mdb
fi
cp Cobra.Lang.dll $target/
cp styles-cobra-doc.css $target/
cp styles-cobra-shl.css $target/
cp styles-output-html.css $target/
cp styles-exception-report.css $target/
cp -pr Cobra.Lang/*.cs $target/Cobra.Lang
cp -pr Cobra.Lang/*.cobra $target/Cobra.Lang
cp -pr Cobra.Lang/*.text $target/Cobra.Lang
echo date is `date`
cmd="ls -l $target"
echo $cmd
$cmd
