#!/bin/bash
# TODO: enhance to cp new into old-snapshots
mkdir -p new
cp cobra.exe new/
if [ -e cobra.pdb ]
	then
		cp cobra.pdb new/
	else
		rm -f new/cobra.pdb
fi
if [ -e cobra.mdb ]
	then
		cp cobra.mdb new/
	else
		rm -f new/cobra.mdb
fi
cp CobraInfo.cs new/
cp CobraLang.cs new/
cp CobraLang.cobra new/
cp SystemInterfaces.cobra new/
