#!/bin/bash
# TODO: enhance to cp new into old-snapshots
target='snapshot'
mkdir -p $target
cp cobra.exe $target/
if [ -e cobra.pdb ]
	then
		cp cobra.pdb $target/
	else
		rm -f $target/cobra.pdb
fi
if [ -e cobra.mdb ]
	then
		cp cobra.mdb $target/
	else
		rm -f $target/cobra.mdb
fi
cp CobraInfo.cs $target/
cp CobraLang.cs $target/
cp CobraLang.cobra $target/
cp SystemInterfaces.cobra $target/
cp output-html-styles.css $target/
echo date is `date`
cmd='ls -l snapshot'
echo $cmd
$cmd
